{% set name = "epics-pypdb" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/epics-pypdb/archive/{{ version }}.tar.gz
  sha256: c23c9bcb52ecbd71a4f07d9919a1460d95c53d4f899cfa6b03bd153d285972e0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - ply
  run:
    - python
    - ply

test:
  commands:
    - python -m nose pyPDB

  requires:
    - nose

about:
  home: https://github.com/pcdshub/epics-pypdb
  license: EPICS Open
  license_family: Other
  license_file: LICENSE
  summary: Python tools for EPICS Process Database
  description: |
    Python tools for EPICS Process Database
  dev_url: https://github.com/pcdshub/epics-pypdb

extra:
  recipe-maintainers:
    - hhslepicka 
    - klauer
